create table if not exists public.stats_events(id bigint generated by default as identity primary key,event_type text not null check(event_type in('access','open')),access_code_id uuid references public.access_codes(id) on delete set null,link_id uuid references public.links(id) on delete set null,link_item_id uuid references public.link_items(id) on delete set null,country text,region text,city text,user_agent text,created_at timestamptz not null default now());
create index if not exists stats_events_created_idx on public.stats_events(created_at desc);
create index if not exists stats_events_code_idx on public.stats_events(access_code_id,created_at desc);
create index if not exists stats_events_item_idx on public.stats_events(link_item_id,created_at desc);
alter table public.stats_events enable row level security;
revoke all on table public.stats_events from anon,authenticated;
grant all on table public.stats_events to service_role;
notify pgrst,'reload schema';
